DROP SCHEMA IF EXISTS PAYMENT_SYSTEM_DB;
CREATE SCHEMA IF NOT EXISTS PAYMENT_SYSTEM_DB;

DROP TABLE IF EXISTS PAYMENT_SYSTEM_DB.bank_accounts;
DROP TABLE IF EXISTS PAYMENT_SYSTEM_DB.merchant;
CREATE TABLE IF NOT EXISTS PAYMENT_SYSTEM_DB.bank_accounts(
    id VARCHAR(60) NOT NULL,
    merchant_id VARCHAR(60) NOT NULL,
    status VARCHAR(10) NOT NULL,
    account_number VARCHAR(60) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS PAYMENT_SYSTEM_DB.merchants(
    id VARCHAR(60) NOT NULL,
    name VARCHAR(60) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id));