DROP SCHEMA IF EXISTS users_db;
CREATE SCHEMA IF NOT EXISTS users_db;
DROP TABLE IF EXISTS users_db.users;
CREATE TABLE IF NOT EXISTS users_db.users(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
password VARCHAR(10) NOT NULL,
PRIMARY KEY (id));
